-- Generated by SQL Maestro for MySQL. Release date 14/04/2009
-- 23/05/2011 11:06:25 a.m.
-- ----------------------------------
-- Alias: cristorey at localhost
-- Database name: cristorey
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.0.51b-community-nt-log
-- Session ID: 3
-- Character set: utf8
-- Collation: utf8_general_ci


DROP DATABASE IF EXISTS `cristorey`;

CREATE DATABASE `cristorey`
  CHARACTER SET `utf8`
  COLLATE `utf8_general_ci`;

USE `cristorey`;

/* Tables */
DROP TABLE IF EXISTS `costo`;

CREATE TABLE `costo` (
  `idcosto`      int AUTO_INCREMENT NOT NULL,
  `descripcion`  varchar(220) NOT NULL,
  PRIMARY KEY (`idcosto`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `proyecto`;

CREATE TABLE `proyecto` (
  `idproyecto`   int AUTO_INCREMENT NOT NULL,
  `descripcion`  varchar(220) NOT NULL,
  `fecha`        date NOT NULL,
  `monto`        decimal(10,2),
  PRIMARY KEY (`idproyecto`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `proyectocosto`;

CREATE TABLE `proyectocosto` (
  `idpc`        int AUTO_INCREMENT NOT NULL,
  `idproyecto`  int NOT NULL,
  `idcosto`     int NOT NULL,
  `monto`       decimal(10,2) NOT NULL,
  `cantidad`    decimal(10,2) NOT NULL,
  PRIMARY KEY (`idpc`)
) ENGINE = InnoDB;

/* Procedures */
DROP PROCEDURE IF EXISTS `eliminarcosto`;

DELIMITER |

CREATE PROCEDURE `eliminarcosto` 
(
  IN `id` int
)
BEGIN
  DELETE FROM costo WHERE costo.`idcosto`=`id`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `eliminarpc`;

DELIMITER |

CREATE PROCEDURE `eliminarpc` 
(
  IN `id` int
)
BEGIN
  DELETE FROM proyectocosto WHERE proyectocosto.`idpc`=`id`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `eliminarproyecto`;

DELIMITER |

CREATE PROCEDURE `eliminarproyecto` 
(
  IN `id` int
)
BEGIN
  DELETE FROM proyecto WHERE proyecto.`idproyecto`=`id`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `listarCosto`;

DELIMITER |

CREATE PROCEDURE `listarCosto` ()
BEGIN
SELECT * FROM costo;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `listarpc`;

DELIMITER |

CREATE PROCEDURE `listarpc` 
(
  IN `idproy` int
)
BEGIN
  SELECT p.`idproyecto`,p.`descripcion`,p.`fecha`,p.`monto`,c.`idcosto`,c.`descripcion`,pc.`idpc`,pc.`monto` as costo,pc.`cantidad` FROM
proyectocosto pc INNER JOIN proyecto p ON pc.`idproyecto`=p.`idproyecto` INNER JOIN costo c ON
  c.`idcosto`=pc.`idcosto` WHERE pc.idproyecto=`idproy`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `listarproyecto`;

DELIMITER |

CREATE PROCEDURE `listarproyecto` ()
BEGIN
  SELECT * FROM proyecto ORDER BY proyecto.`fecha` desc;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `modificarcosto`;

DELIMITER |

CREATE PROCEDURE `modificarcosto` 
(
  IN  `id`    int,
  IN  `desc`  varchar(200)
)
BEGIN
  UPDATE costo SET costo.`descripcion`=`desc` WHERE costo.`idcosto`=`id`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `modificarproyecto`;

DELIMITER |

CREATE PROCEDURE `modificarproyecto` 
(
  IN  `id`        int,
  IN  `desc`      varchar(200),
  IN  `fech`      date,
  IN  `cantidad`  decimal(10,2)
)
BEGIN
  UPDATE proyecto SET proyecto.`descripcion`=`desc`,proyecto.`fecha`=`fech`,proyecto.`monto`=`cantidad` WHERE proyecto.`idproyecto`=`id`;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `numRegCosto`;

DELIMITER |

CREATE PROCEDURE `numRegCosto` ()
BEGIN
SELECT COUNT(*) FROM costo;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `numregproy`;

DELIMITER |

CREATE PROCEDURE `numregproy` ()
BEGIN
  SELECT COUNT(*) FROM proyecto;
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `registrarcosto`;

DELIMITER |

CREATE PROCEDURE `registrarcosto` 
(
  IN `desc` varchar(200)
)
BEGIN
INSERT INTO  `costo` (
`descripcion`
)
VALUES (`desc`);
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `registrarpc`;

DELIMITER |

CREATE PROCEDURE `registrarpc` 
(
  IN  `idproy`  int,
  IN  `idcost`  int,
  IN  `precio`  decimal(10,2),
  IN  `cant`    decimal(10,2)
)
BEGIN
  INSERT INTO proyectocosto(proyectocosto.`idproyecto`,proyectocosto.`idcosto`,proyectocosto.`monto`,proyectocosto.`cantidad`)
  VALUES(`idproy`,`idcost`,`precio`,`cant`);
END|

DELIMITER ;

DROP PROCEDURE IF EXISTS `registrarproyecto`;

DELIMITER |

CREATE PROCEDURE `registrarproyecto` 
(
  IN  `desc`      varchar(200),
  IN  `fecha`     date,
  IN  `cantidad`  decimal(10,2)
)
BEGIN
  INSERT INTO proyecto(proyecto.`descripcion`,proyecto.`fecha`,proyecto.`monto`)
  VALUES(`desc`,`fecha`,`cantidad`);
END|

DELIMITER ;

/* Indexes */
CREATE UNIQUE INDEX `descripcion`
  ON `costo`
  (`descripcion`);

CREATE INDEX `idcosto`
  ON `proyectocosto`
  (`idcosto`);

CREATE INDEX `idproyecto`
  ON `proyectocosto`
  (`idproyecto`, `idcosto`);

/* Foreign Keys */
ALTER TABLE `proyectocosto`
  ADD CONSTRAINT `proyectocosto_ibfk_1`
  FOREIGN KEY (`idproyecto`)
    REFERENCES `proyecto`(`idproyecto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

ALTER TABLE `proyectocosto`
  ADD CONSTRAINT `proyectocosto_ibfk_2`
  FOREIGN KEY (`idcosto`)
    REFERENCES `costo`(`idcosto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

/* Data for table "costo" */
INSERT INTO `costo` (`idcosto`, `descripcion`) VALUES (4, 'costo');
INSERT INTO `costo` (`idcosto`, `descripcion`) VALUES (5, 'costo1');
INSERT INTO `costo` (`idcosto`, `descripcion`) VALUES (6, 'costo2');
COMMIT;


/* Data for table "proyecto" */
INSERT INTO `proyecto` (`idproyecto`, `descripcion`, `fecha`, `monto`) VALUES (2, 'jona', '2011-05-13', 2000);
COMMIT;


/* Data for table "proyectocosto" */
INSERT INTO `proyectocosto` (`idpc`, `idproyecto`, `idcosto`, `monto`, `cantidad`) VALUES (1, 2, 4, 12, 12);
INSERT INTO `proyectocosto` (`idpc`, `idproyecto`, `idcosto`, `monto`, `cantidad`) VALUES (2, 2, 5, 12, 12);
INSERT INTO `proyectocosto` (`idpc`, `idproyecto`, `idcosto`, `monto`, `cantidad`) VALUES (3, 2, 6, 12, 1);
COMMIT;
